%global release_version %%(echo %{version} | awk -F. '{print $1"."$2}')

Name: devhelp
Version: 3.16.0
Release: 1%{?dist}
Epoch: 1
License: GPLv2+
Group: Development/Tools
Summary: API documention browser
URL: http://live.gnome.org/devhelp
#VCS: git:git://git.gnome.org/devhelp
Source: http://download.gnome.org/sources/devhelp/%{release_version}/devhelp-%{version}.tar.xz

Requires(post):   /usr/bin/gtk-update-icon-cache
Requires(postun): /usr/bin/gtk-update-icon-cache

%description
Devhelp is an API documentation browser for the GNOME desktop.
It works natively with API documentation generated by gtk-doc.

%package libs
Summary: Runtime libraries for devhelpe
Group: Development/Libraries

%description libs
Devhelp is an API documentation browser for the GNOME desktop.
This package contains a library that can be used for embedding devhelp
into other applications such as IDEs.

%package dev
Summary: Library to embed Devhelp in other applications
Group: Development/Libraries
Requires: %{name}-libs%{?_isa} = %{epoch}:%{version}-%{release}

%description dev
Devhelp is an API documentation browser for the GNOME desktop.
This package contains a library that can be used for embedding devhelp
into other applications such as IDEs.

%prep
%setup -q

%build
%configure --disable-static
make %{?_smp_mflags} CFLAGS="$CFLAGS -fno-strict-aliasing"

%install
make install DESTDIR=$RPM_BUILD_ROOT

find ${RPM_BUILD_ROOT} -type f -name "*.la" -exec rm -f {} ';'

mkdir -p $RPM_BUILD_ROOT%{_datadir}/devhelp/books

chrpath --delete $RPM_BUILD_ROOT%{_bindir}/devhelp

%find_lang devhelp

desktop-file-validate $RPM_BUILD_ROOT%{_datadir}/applications/devhelp.desktop

%post
/sbin/ldconfig
touch --no-create %{_datadir}/icons/hicolor >&/dev/null || :

%postun
/sbin/ldconfig
if [ $1 -eq 0 ]; then
  glib-compile-schemas %{_datadir}/glib-2.0/schemas >&/dev/null || :
  touch --no-create %{_datadir}/icons/hicolor >&/dev/null || :
  gtk-update-icon-cache %{_datadir}/icons/hicolor >&/dev/null || :
fi

%posttrans
gtk-update-icon-cache %{_datadir}/icons/hicolor >&/dev/null || :

%posttrans libs
glib-compile-schemas %{_datadir}/glib-2.0/schemas >&/dev/null || :


%files -f devhelp.lang
%doc AUTHORS COPYING NEWS README misc/devhelp.{el,vim}

%{_bindir}/devhelp

%{_datadir}/applications/devhelp.desktop
%{_datadir}/appdata/devhelp.appdata.xml
%{_datadir}/GConf/gsettings/devhelp.convert
%{_datadir}/icons/hicolor/16x16/apps/devhelp.png
%{_datadir}/icons/hicolor/22x22/apps/devhelp.png
%{_datadir}/icons/hicolor/24x24/apps/devhelp.png
%{_datadir}/icons/hicolor/32x32/apps/devhelp.png
%{_datadir}/icons/hicolor/48x48/apps/devhelp.png
%{_datadir}/icons/hicolor/256x256/apps/devhelp.png

%dir %{_libdir}/gedit
%dir %{_libdir}/gedit/plugins
%{_libdir}/gedit/plugins/devhelp.*

%files libs
%{_libdir}/libdevhelp*.so.*
%{_datadir}/devhelp
%{_datadir}/glib-2.0/schemas/org.gnome.devhelp.gschema.xml

%files dev
%{_prefix}/include/devhelp-3.0
%{_libdir}/libdevhelp*.so
%{_libdir}/pkgconfig/*

%changelog
* Fri Mar 27 2015 Alexander Larsson <alexl@redhat.com> - 1:3.16.0-1
- Initial version
